### ISSUE TITLE
Citation of protein fragment dataset

### ISSUE THREAD

**Issue by davkovacs** [openmm/spice-dataset#58]
I think this dataset from PhysNet would be worth at least a mention in the paper and perhaps could be considered for recomputing and adding (part of) it to SPICE: 

https://zenodo.org/record/2605372#.Y3uiNS8w0Q0

**Comment by peastman** [comment]
Does that dataset provide any information beyond what we already have in the dipeptides and solvated amino acids subsets?  It looks like they mainly designed it to keep the molecules as small as possible so the DFT calculations would be fast.  Their fragments have a maximum of eight heavy atoms, and even with solvent there's a maximum of 21 heavy atoms.  That makes it fast, but at the cost of providing a less realistic representation of proteins than what you get with complete amino acids and dipeptides.

**Comment by davkovacs** [comment]
FYI the paper contains a detailed discussion of the dataset and how it was generated. 
https://pubs.acs.org/doi/pdf/10.1021/acs.jctc.9b00181

**Comment by peastman** [comment]
They generated their conformations by simulating each molecule for 100 fs and saving a conformation every 1 fs.  That's far too short to sample much beyond bond length and angle oscillations.  And they started each simulation from an energy minimized conformation rather than an equilibrium one.  They have a lot of conformations, but they're all clustered in a small region around the energy minimum.
